#!/bin/bash
#SBATCH --account=plgccbmc14-cpu
#SBATCH --partition=plgrid
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=48
#SBATCH --mem-per-cpu=2000
#SBATCH --time=11:35:00
#SBATCH --job-name=batch{batch_num}

module load hyperqueue

export HQ_SERVER_DIR="$PWD/hq-server/$SLURM_JOB_ID"
mkdir -p "$HQ_SERVER_DIR"

hq server start &
until hq job list &> /dev/null ; do sleep 1 ; done

srun --overlap --cpu-bind=none --mpi=none hq worker start \
  --manager slurm \
  --on-server-lost finish-running \
  --cpus="$SLURM_CPUS_PER_TASK" &


hq worker wait "$SLURM_NTASKS"

hq submit --cpus=1 --array=0-{num_simulations} {home}/run_shieldhit_cyfronet_batch{batch_num}.sh

echo "=== JOBS ==="
hq job list
echo "=== WORKERS ==="
hq worker list
echo "=== JOB DETAILS ==="
hq job info 1

hq job wait all

hq worker stop all
hq server stop
